package shaders
/*
    #version:1# (machine generated, don't edit!)

    Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

    Cmdline:
        sokol-shdc --input ./shared.glsl --output generated_shared.odin --slang glsl430:glsl300es --format sokol_odin

    Overview:
    =========
    Bindings:
*/
